### ISSUE TITLE
Option\Open Context at Startup

### ISSUE THREAD

**Issue by jspencer46** [sedenion/OpenModMan#1]
This option does not seem to work, or at least I can not determine how to make it work.

**Comment by sedenion** [comment]
Sorry for the time to answer.

You probably already did this but to be sure I specify the process:
1. check the "Open Contex(s) at startup" check box
2. Click the "Add.." button, then choose an existing Context (.omc) file
3. Click "Apply" or "OK"

Normaly, the next time you open the software, the selected Context file will open automatically.

If this is not what happen on your side, please give me some details.

**Comment by lorthirk** [comment]
I'm having this issue as well. The problem is that when I set a Context to be opened at startup, the next time I open OMM the entry is there but it's empty:

![image](https://user-images.githubusercontent.com/8140139/101289833-0f6e3100-37ff-11eb-80fc-b34023558065.png)

And, of course, it doesn't open at startup.

**Comment by sedenion** [comment]
Problem identified and solved for the next release.
