### ISSUE TITLE
When using a network repo hosted on github I always get checksum mismatch

### ISSUE THREAD

**Issue by deephack1982** [sedenion/OpenModMan#12]
```
<?xml version="1.0"?>
<Open_Mod_Manager_Repository>
  <uuid>0f03dbf5-2690-472a-adb1-a80b513b5234</uuid>
  <title>VAF Repo</title>
  <downpath>files/</downpath>
  <remotes count="2">
    <remote ident="2_squadron" file="2_squadron.zip" bytes="277422609" checksum="cf3fe9889358bf25">
      <url>https://github.com/virtualairforce/mod-repo/raw/main/repo/</url>
    </remote>
    <remote ident="3_squadron v1.4" file="3_squadron v1.4.zip" bytes="272434420" checksum="91baab7b38385b6c83c9fcd46959d538">
      <url>https://github.com/virtualairforce/mod-repo/raw/main/repo/</url>
    </remote>
  </remotes>
</Open_Mod_Manager_Repository>
```

Using the above xml when I try to download either of the mods I always get this message. Is this an issue with hosting on github or something else?

[18:48:20]XX Manager:: Context(Test):: Location(DCS):: Remote(3_squadron v1.4) Download:: Downloaded file checksum mismatch the reference

**Comment by deephack1982** [comment]
Note that the 2_squadron checksum is the original as created using the GUI. The one for 3_squadron I calculated by hand and edited in. Neither works.

**Comment by sedenion** [comment]
At first glance the checksum mismatch is only a side effect, the main problem is that what you downloaded (as client) was NOT the intended files. This, probably because you specified an invalid custom URL for both files. 
When you specify custom URL for a file, you must specify the FULL URL to the file to download, so, including file name (yes, I know, this is specified nowhere... my bad). In the present case, the manager downloaded the github page, which obviously mismatch the file to download.

Finaly, the checksum you manualy computed appear to be not computed using the proper hash algorithm. Open Mod Manager use 64 bits xxHash ( XXH3_64bits ) algorithm to compute checksum, you can found implementation here : 
https://github.com/sedenion/OpenModMan/blob/master/src/OmGlobal.cpp#L277
https://github.com/sedenion/OpenModMan/blob/master/src/OmGlobal.cpp#L305
https://github.com/pombredanne/xxHash-3

**Comment by deephack1982** [comment]
Ah thank you for the quick response. I didn't understand that I should be using the full url. I've updated my xml to look like this now.

```
<?xml version="1.0"?>
<Open_Mod_Manager_Repository>
  <uuid>0f03dbf5-2690-472a-adb1-a80b513b5234</uuid>
  <title>VAF Repo</title>
  <downpath>files/</downpath>
  <remotes count="2">
    <remote ident="2_squadron" file="2_squadron.zip" bytes="277422609" checksum="cf3fe9889358bf25">
      <url>https://github.com/virtualairforce/mod-repo/raw/main/repo/2_squadron.zip</url>
    </remote>
    <remote ident="3_squadron v1.4" file="3_squadron v1.4.zip" bytes="272434420" checksum="96fab37db8d6d8a2">
      <url>https://github.com/virtualairforce/mod-repo/raw/main/repo/3_squadron%20v1.4.zip</url>
    </remote>
  </remotes>
</Open_Mod_Manager_Repository>
```

I can copy paste these urls into a browser and the files download normally however I still get the same checksum error in open mod manager. I've reverted the checksums to be the ones generated by the mod manager.

**Comment by sedenion** [comment]
Ok, The problem is that requesting file via the URL _https://github.com/virtualairforce/mod-repo/raw/main/repo/_ actualy responds with a 302 redirect, and this is the 302 redirect response that Open Mod Manager actually download and compare to file checksum (and logically comparison fail). The real URL to download file actually are 
**https://raw.githubusercontent.com/virtualairforce/mod-repo/main/repo/**

Open Mod Manager does not handle HTTP redirect curently, I thought it was not really useful, but it seem the case is more frequent than I though

**Comment by sedenion** [comment]
I added support for automatic redirect follow, this will be functionnal in the next release.
