### ISSUE TITLE
Snapshot image is stored in full size in the zip and not the thumbnail that is created

### ISSUE THREAD

**Issue by retroluxfilm** [sedenion/OpenModMan#19]
I noticed while working on the Php OMM repository library that when the image is bigger than the 128pixels it creates a thumbnail but dont use that thumbnail to store it in the package zip (snapshot.jpg). Instead it uses the full size image creating a larger package. 

In the repository xml the right thumbnail data is used. Just wondered why my repository xmls got so huge creating them in PHP.

**Comment by sedenion** [comment]
Yes, this is intended. For package, the original imag, at its original size and format (bmp, png, jpeg or gif) is stored. So the package maintainer is free to embed a big, small high or low quality image. The image is then "thumbnailed" in order to be displayed within GUI.

However, since the repository XML file is intended to be downloaded, and may embed a lot of packages with their own snapshot and description, the choice was to convert source image to 128 pixels large JPEG format with a somewhat low quality.

**Comment by retroluxfilm** [comment]
That makes sense. I have now replicated this behaivor on the PHP side as well to include only a thumbnail out of the snapshot image in the repository xml.

I plan to release the PHP Web repository library soon on github. Was more work than I thought initially as I am not used to programm php.
