### ISSUE TITLE
Mod-Directory xml format

### ISSUE THREAD

**Issue by schradj** [sedenion/OpenModMan#22]
I've got a repo working using the mod-archive format where it is zipped up with a version and readme file.  We have some mods we would prefer to leave unzipped, but I can't figure out how to properly include a mod-directory (unzipped).  It is being listed but ends up downloading a corrupt .zip file.  Is there something I need to adjust in the xml or how the mod is stored? 

  `<mod name="VF-84_Liveries" version="1.0.3" url="myurl/ovgme/Mod_Repo/VF-84_Liveries/">VNAO CVW-7 VF-84 Jolly Rogers skin set for the F-14B</mod>`
  
  thanks

**Comment by sedenion** [comment]
First, what you are trying to do is simply not possible. Secondly, you are talking about OvGME which is an old program, this github repository is about Open Mod Manager, its successor, did you tryed it ? Event in the more advanced Open Mod Manager what you are trying to do is not possible.

**Comment by schradj** [comment]
Yes, I know, I apologize for using this for an OvGME question, but with that repo closed, this was the only way I could think of to get a hold of you.  I have tried OMM and I got the write permissions error.  I saw a lot of people commenting that they had this issue.  While I would like to move to a mod manager tool that's actively supported by its developer, I cannot ask the over 100 members of my DCS group to switch to a new tool if there's a high likelihood of many of them running into bugs.  Will continue to monitor the development of this tool.   I understand your desire to move on to your new idea but OvGME is from what I can tell still the predominant mod manager tool for the DCS community.

**Comment by sedenion** [comment]
### The TLDR; Version:

The permission error is NOT a bug, this is an intended behavior (yes, you well read), you can normaly easily workaround this like for any other program by __running it as Administrator__. You can do this either:

* **Temporarly** via the shortcut's contextual menu
    - Right click on shortcut or shift + right-click on task bar icon. 
    - Select "Run as administrator"
* **Permanently** by setting shortcut's advanced option
  - Right click on shortcut or shift + right-click on task bar icon. 
  - Select "Properties"
  - Go to the "Shortcut" tab and click "Advanced" button.
  - Select "Run as administrator"
* **Permanently** by setting programa's Compatibily option
  - Right click on shortcut or shift + right-click on task bar icon. 
  - Select "Properties"
  - Go to the "Compatibility" tab and check "Run this program as an Adaministrator" **OR** Clic the Modify settings for all users" then check "Run this program as an Adaministrator".

These options are the proper way to do what is named a __privileges escalation__.

### The long Answere:

As said, the write permission error is NOT a bug anymore since the 0.9.1 release (two years ago). Open Mod Manager relly on process and system security tokens to check its own permissions. In other words, Open Mod Manager simply asks the system - in the proper and standard way - "Do I have permission to do this ?", and the system respond Yes or No, that's all. Open Mod Manager is not responsible of what the system repond when it ask for permission, the USER is reponsible.

This usualy occure when you work within system's special folders (C:\Programs, C:\Windows, etc.) which have actually user access restrictions defined by system design - by Microsoft itslef - to prevent user to alter sensitive files without caution. This also may appen if a folder have special user defined permissions, which in some case, considering various security or priority contexts (And believe me, under Windows this is gigantic puzzle), may prevent the program to have read or write access to this particular folder. Again, as I said Open Mod Manager simply asks the system for its own permissions, it is not responsible for what the system returns, the USER is.

**Now, you will ask, WHY in this case this do not occur with OvGME ?** Because OvGME was compiled with a specific value in its "Application Manifest" that ask for privilege escalation prior to run the program (the program need privilege escalation to run, or it don't run). That is why, when you run OvGME you see the famous "User Account Control" popup dialog that ask you if you allow this program to make changes to your computer. You can reproduce the exactly same behavior by setting the "Run as administraor" options as described above.

**Finally , why do not compile Open Mod Manager with that same "Application Manifest" value that force privileges escalation ?** By choice of mine, in accordance to security consideration and "good practices" philosophy: 
* A program __SHOULD NOT forces user to accept privileges escalation to run__, this is by definition a suspicious practice (and users SHOULD care about this kind of behavior) unless the purpose of the program was precisely to alter system's sensitive elements.
* The users __SHOULD be aware of what they do__, and alter running privileges conciously. The system is designed - theoretically (Windows and securitu is a vast joke) - for that to prevent malicious behavior and warn user that he try to alter somethin that is is outside its enclosure.
* Considering that how easy it is to configure automatic privilege escalation, as described above, there is no rational reason to force user to did it in a "falsely transparently", unless to let users in the ignorance of how their system works, and precisely, I don't like to let people in ignorance.

I hope you now understands what all this thing is about, there is no bug related to "permissions", this is user responsability, but, in many cases, user even don't understand how their system are configured and how it works, and **this is bad**. If people are complaining about this "privliges error", you can copy-past the explanation above.
