### ISSUE TITLE
What's the right way to update packages in the repo?

### ISSUE THREAD

**Issue by schradj** [sedenion/OpenModMan#38]
I have new liveries to update an existing livery pack.  I create a new archive with the exact same name, but incremented version number.
When I add the new one to the repo listing, it's additive and lists the new version separately, so I remove the old version.  As the client, when I download the new version, it is also treating it as a separate mod.  So i end up with two mods, the old and the new one.  Installing the new one gives me a warning about it overwriting files from another mod (the old version of the livery pack)

**Comment by sedenion** [comment]
If the two versions have the same core name, the manager should detect it and allow user to "upgrade" instead of "download". In this case the old package present in Library is renamed (by default) or moved to trash (if proper parameter is set). Also, if package is detected as newer version and user double-click on package, the manager show a message dialog to ask user if it want to keep the older version. Ensure that the "core name" of both packages are really the same.
