### ISSUE TITLE
Feature: Write package version in definition file

### ISSUE THREAD

**Issue by lorthirk** [sedenion/OpenModMan#4]
I think it should be cleaner to set the Version of a package in the Definition file, rather than inferring it from the file name. This way, the version is decoupled from the file name. Maybe you could support the inferred version only if no value has been set in the Definition file.

**Comment by BlueFinBima** [comment]
+1 for this.

**Comment by sedenion** [comment]
Ok, I will try to explain why I choosen the versionning via file name. Actually, it hase many advantages. 

- This allow to create a mod manually with the proper version, you are not forced to use the "Package creator" to properly set a version of your mod, you are not forced to create a definition file. This is way more natural.

- You instantly can know the version of the mod by simply checking its filename, no need to enter the zip file and inspect any XML definition file or opening it within the proper specific software which will be the only one to properly parse the version within the definition file: more open, more transparent,  more simple.

- Including the version in the package file name is already a natural practice for many mod creators, and actually this is a good practice, this helps organization.

- This allow to easily create dependencies links based only on the package file name, without even version checking: The "good version" has the "good filename", all other are not. This is all way more simple like that, for me (software developper) as for mod/package creators/mainteners. With or without version of any format, all work the same way, because all is based on the file name.

- The same logic apply to the futur network repository managament, this avoid storing two separated values and checking against two values in the prior check.

- This allow to store multiple versions of the same mod with the same name within the same Library folder or network repository, because each version have an unique file name. You can have several versions of the same mod, enabling or disabling the one you want.

- This way, even mods as folder can have a version, and this is very valuable for mod creators. When you create a mod, you first create a developement version, as a "folder", then you can duplicate the folder to create a new version, keeping the old one, and create multiple versions for testing. This make the versioning and organisation for mod creators a lot more easy and flexible.

So, knowing this: Why do you want this version to be hiden, hard to verify and to change, within an obscure XML file ?

**Comment by BlueFinBima** [comment]
Hi, thank you for describing your thinking.  Perfectly understandable
rationale.  The problem is that there are still many packages without
versioning in the filename.  I think that filename versioning should take
precedence, however if it cannot be determined from the filename, there
should be an option to add the version into the package without changing
the filename.  This would provide a way to version the package, and keep
the author's original name.
Many thanks for continuing the great work started with OVGME.  BFB

**Comment by sedenion** [comment]
Ok, can you explain me:
- Why do you need to add a version to a package ? (packages without version work fine)
- Why the package name must be the same as the "author's original name" ?
