### ISSUE TITLE
v 1.0.8 does not retain Developer mode (parse subfolders) option on restart

### ISSUE THREAD

**Issue by SPAS79** [sedenion/OpenModMan#46]
If selected (under Edit->Channel->Properties) Developer mode (for displaying folders alongside packages does not "stick". 

When closed and open again the application shows the folders as missing until developer mode is enabled again. 

The issue is present both if the application is started with normal or elevated privileges (admin). 

Keeping the option as set by the user is the expected behavior as 1.0.3 (in use before 1.0.8)  retained the setting / displayed folders consistently.

**Comment by sedenion** [comment]
Ok, I found the bug, it is due to wrong config file init procedure introduced with new "Show Hidden Files" option.

You can workaround by enabling "Show Hidden Files" (it is in the same propertie dialog than "Developper Mode"), then closing properties dialog (so the propertie is written in config fie). Once done, you can open the properties dialog and disabling "Show Hidden Files" again.
