### ISSUE TITLE
Downloading (repository) large (0.5-3.5GB) files can lock up OMM and then crash it

### ISSUE THREAD

**Issue by ChaosRifle** [sedenion/OpenModMan#51]
a DCS group I am part of has a lot of liveries and aircraft mods in it, and downloading the UH60 for example is quite the task, as you need to hit download some 5-6 times, because it crashes before done downloading and you need to start over. also had one crash while processing, but dozens while downloading mods. Very repeatable.

**Comment by sedenion** [comment]
Hi,

I see two possibilities for what you describe, either you used the 32bit version which is, after investigation, indeed buggy due to wrong files size handling, or you try to save downloaded file on a FAT32 file system. 

Anyway, you can try with the latest 1.1.1 release, I made subsential modification of the download process, now implementing download resum mechanism and fixed bug related to files size in 32bit system.

**Comment by ChaosRifle** [comment]
will do, I think I am on 64bit 1.0.8, but not sure how to check for 32 bit. Thanks for looking into it!
