### ISSUE TITLE
Getting unexplained Mod download error following update to 1.2.1

### ISSUE THREAD

**Issue by hbjonsson** [sedenion/OpenModMan#57]
Following the update to 1.2.1 I´mg etting unexplained Mod download errors from repositories that were working before.

Have done a reinstall to no avail. The message offers no insight as to why it failed and the debug log shows nothing.

![image](https://github.com/sedenion/OpenModMan/assets/25992707/1f0262b4-bda6-4f29-9c38-6a5b4f486826)

The repository validates ok - running as admin has no effect. Zero byte files get added to the /Library folder and the download appears failed. Any idea on further debugging/troubleshooting?

**Comment by sedenion** [comment]
please give repository address/coordinates and name of the mod so I can test myself and investigate.

**Comment by hbjonsson** [comment]
@sedenion Here is the link - any one of the mods will fail.

https://cloud.455aew.com/apps/sharingpath/public/repo/455_savegames_repo.omx

**Comment by sedenion** [comment]
Ok, it's because Open Mod Manager does not encode special characters of the URL (like space to %20 for example) and it never did. And the fact is that Mods names in your repository contains spaces.

Internally I corrected error dialog so it give some clue about what failed and added a rudimentary URL encoding routine. On your side, until I release a new version, I suggest you change Mod names, replacing spaces by underscores "_", or adding custom download URL for each Mod of your repository, replacing spaces by "%20"

**Comment by hbjonsson** [comment]
Thanks,. I´ll try custom download URL. I fixed the repo and mod names/paths to not have any spaces and am still getting the same errors, in case you want to look again.

**Comment by hbjonsson** [comment]
@sedenion Can confirm that the custom url works. Without the custom url, OMM seems to inject the name of the repo file itself into the path.
