### ISSUE TITLE
Possible issue: OMM losing setting to apply mod at startup

### ISSUE THREAD

**Issue by TheTurbs** [sedenion/OpenModMan#76]
Not sure if this has been discovered or is a potential issue.  Our group recently switched over to OMM and we've been migrating members over.  As part of our instructions we had members setup OMM to load the game hub automatically on OMM startup.  However we've seen 3 or 4 cases now where we apply the settings to auto load the game hub, but on OMM program restart, the mod hub is not displayed nor is the setting to apply the mod hub on startup even set.  It's as if OMM forgot the settings we applied.

In our instructions we state to check "Open Mod Hub at Startup", Select the game mod hub in question, then click "Apply" then "close"

I've visually confirmed this with 2 other people, but we've seen this happen 3 or 4 times now.

**Comment by sedenion** [comment]
I checked the code and I see no reason such thing would happen except if main configuration file failed to be saved, or loaded, either because of read/write error or user changes between two sessions (since configuration is saved per-user).

This specific configuration data is stored in X:\Users\<usrname>\AppData\Roaming\Open Mod Manager\config.xml check here and see by yourself what could have happended...

Without more information or way to reproduce the bug, I cannot help more.

**Comment by TheTurbs** [comment]
Hi Sedenoin.  We had another person report the same issue tonight.  I compared their config file vs. mine and it appears empty.  I know this person had it setup correctly 2-3 days ago cause I monitored them do it.
<img width="1650" alt="Capture" src="https://github.com/sedenion/OpenModMan/assets/122108095/10763fc1-7e7d-46fd-8b2b-e9676c500ccd">
