### ISSUE TITLE
Target Directory Access Error

### ISSUE THREAD

**Issue by Mkel2010** [sedenion/OpenModMan#78]
I previously had OVGME installed but was having problems with some mods that stopped being recognized by DCS World. I downloaded Open Mod Manager today and set it up with the same DCS Mods. After turning on the mods I opened DCS and confirmed they were working. I closed down both OMM and DCS and then deleted OVGME. I  later opened DCS and checked one of the mods to make some changes in game and found it wasn't there. I went back into OMM and found that neither of the two hubs I created for DCS (a Main and a Saved Game hub) showed up on opening. I found I could access the Saved Game Hub but when I tried to access the Main hub (pointed to /Program Files/DCS World, I received a Target Directory Access Error with the following text:

The Target Directory cannot be accessed because it does not exist or have read write access restrictions. Please check Mod Channel settings and directory permissions.

C:\Program Files\Eagle Dynamics\DCS World.

I didn't get this error before deleting the old OVGME installation so I'm not sure if that's related. The DCS World directory is marked as Read Only by Windows 11, but so are all the Saved Game directories. This is by default and cannot be changed apparently. 

I've tried creating new hubs without any change.

**Comment by sedenion** [comment]
Try to run OMM as administrator, check your Windows users's permissions setup... This is not a problem related to OMM, OMM only check's whether it has right to read/write... if he can't, he tells you so. 

Such kind of problem occur since I started developping OvGME years ago. Because the first intent of Windows permissions management is to prevent user to administrate their system and people sometimes do things they don't understand (and even don't know), they end up with some specific permission setup that "block" their system at some level... Blame Microsoft, ask them why you don't have permission to administrate your own system as you wish despit the fact you paid for that.

**Comment by Mkel2010** [comment]
The solution was to run OMM as Administrator. I fully agree with your comments about Microsoft. I have none of these issues with MacOS.
