### ISSUE TITLE
Include top level folder

### ISSUE THREAD

**Issue by trichens** [sedenion/OpenModMan#80]
Say you have a folder structure like this
**GameFolder\UserData\Location\Charlotte\TrackFeatures**
and
**GameFolder\UserData\Location\Daytona\TrackFeatures**
etc...

You want to create a separate package for each location.
Currently you need to selct the **Location** folder as the "root" folder
This means you need to remove all other items in the **Location** folder to create a package for each.
Could we not have an option to retain the "top level" folder for each package.
Could then package - in my example - **Charlotte** and have the package include **Charlotte** as the "parent folder" for the package.
This could have a toggle in the packaging options to turn this off - so remains as current - or on

**Comment by sedenion** [comment]
I don't understand what you mean. Why you need to "remove other items" in Location folder ? If your goal is to create mod for the game, following your example you even should better use "UserData" as "root" folder... Please be more precise of what you want to achieve.

**Comment by trichens** [comment]
Hi.
Thanks for getting back to me.
My very top level folder looks like this

In the Locations folder I have some track folders.

That folder has sub-folders


If I want to make a package with JUST the Aldershot folder data is would select just that folder 


The catch is that when I do that OMM uses the Aldershot folder as the root folder NOT the Locations folder that it is in.


What I'd like to be able to do is select the top level Aldershot folder so that it is included in the compressed package.

As it stands, if I have 20 sub-folders in the Locations folder, I can't create them as separate packages without "hiding" the sub-folders I don't want.
I'd like to create a separate Aldershot.ozp, a separate Barford.ozp, etc. from inside the Locations folder.
If I do this at the moment, the files for the Aldershot package get placed in the Locations folder and not the Aldershot sub-folder when the package in installed through OMM.

I hope that makes sense
Trevor 

On 20/04/2024 06:54:36, Sedenion ***@***.***> wrote:
I don't understand what you mean. Why you need to "remove other items" in Location folder ? If your goal is to create mod for the game, following your example you even should better use "UserData" as "root" folder... Please be more precise of what you want to achieve.

**Comment by sedenion** [comment]
the problem is that you have wrong method to develop and create packages.
What you should do is to create a Channel that is common to any Mod for one game, usually, Game installation folder. From here, inside your OMM's Channe Library folder, create a folder, name it as you futur Mod name (you can change it later). Inside this folder, replicate the tree of folder you need for your mod that directly mirror the Game installation folder. Put your modded files in... 
This way you can : Modify modded file within your OMM Library Folder without acting directly on the game, you can install/uninstall your WIP mod to test and debug it... Once you have done the final mod version, simply create a package from the folder.
