### ISSUE TITLE
[Question] Where are app settings?

### ISSUE THREAD

**Issue by lmiol** [sedenion/OpenModMan#86]
I want to popularize your application. To do this I want to create an Inno Setup installer that comes pre-configured with a hub, channel, and repository for specific game. I plan to implement automatic game path detection, but if unsuccessful, the user can manually select the game's executable file path through the Inno Setup installer. This path will then be written to the channel.omx file.

Currently, I'm unsure how to add the path to "Open Mod Hub at startup". Could you please explain where the application settings, including this option, are stored - whether in the registry or a specific file?

also contact me please [aleksandr.podaruev@gmail.com](mailto:aleksandr.podaruev@gmail.com)
i have a good stuff for you =)

**Comment by sedenion** [comment]
The application settings are located in `%APPDATA%\Open Mod Manager\config.xml` where `%APPDATA%` points (since Windows 10) to current user's Roaming Application Data: `C:\Users\<username>\AppData\Roaming`. To be precise, the application get this path from Windows system by querying constant `CSIDL_APPDATA` ([More details here](https://learn.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shgetfolderpathw)) which may change from a system to another.

The parameters for loaded Hub at startup are the following:
``` xml
  <start_list enable="1">
    <path>C:\Path\To\Your\hub.omx</path>
  </start_list>
```

If you really want to contact me in private, please give me a good reason, because I don't see the need for this. We can discuss here.

**Comment by lmiol** [comment]
> If you really want to contact me in private, please give me a good reason, because I don't see the need for this. We can discuss here.

> i have a good stuff for you =)
thats all what i can say here

**Comment by sedenion** [comment]
Sorry, but this is not sufficient to me. What kind of "stuff", to do what, in what context ?

**Comment by PraetorAugustus** [comment]
> that's all what i can say here. if you interested i can say more in private

Maybe I'm missing something. Why do you need to say more in private? Why not here so other people can contribute suggestions or feature requests?
